"""
Запускайте один раз после git clone:
python initialize_project.py

Он проверит, что все файлы/папки из архитектуры существуют;
если нет – создаст и заполнит минимальным кодом-заглушкой (чтобы проект
был работоспособен даже без реальных секретов).
"""
from pathlib import Path

TREE = {
    "bot_project/main.py": "",
    # остальные файлы перечислять не обязательно – просто пример
}

SKELETON = "# Autogenerated stub\n"

def ensure():
    for rel_path in TREE:
        path = Path(rel_path)
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(SKELETON)
            print("Created", rel_path)

if __name__ == "__main__":
    ensure()
    print("✅ REPO READY")
